jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: opticdev/optic-changelog@36b90003b4d0816fa62eec0dcac358d838c62b69
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          OPTIC_API_KEY: ${{secrets.OPTIC_API_KEY}}